version: '3.1'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: passwd
  back_end:
    depends_on:
      - postgres
    container_name: backend
    build: back_end
    restart: always
  front_end:
    depends_on:
      - back_end
    container_name: frontend
    build: front_end
    restart: always
    environment:
      PORT: 5050
      ORIGIN: "http://localhost:8080"
  proxy:
    container_name: proxy
    depends_on:
      - back_end
      - front_end
    build: nginx
    ports:
      - 8080:8080
