version: '3.1'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: passwd
  back_end:
    depends_on:
      - postgres
    container_name: backend
    build: back_end
    restart: always
    image: gitea.blazanome.ynh.fr/tools/sie_backend:latest
  front_end:
    depends_on:
      - back_end
    container_name: frontend
    build: front_end
    image: gitea.blazanome.ynh.fr/tools/sie_frontend:latest
    restart: always
    environment:
      PORT: 5050
      ORIGIN: "http://localhost:8080"
  proxy:
    container_name: proxy
    depends_on:
      - back_end
      - front_end
    build: nginx
    image: gitea.blazanome.ynh.fr/tools/sie_proxy:latest
    ports:
      - 8080:8080
volumes:
  postgres_data:
