version: '3.1'

services:
  db:
    image: postgres:16.1-alpine3.19
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: passwd
